### ISSUE TITLE
[Bug]: Blue Flame Brazier not ethernal

### ISSUE THREAD

**Issue by PalaNolho** [Digitalroot-Valheim/Digitalroot.Valheim.EternalFire#1]
### How are you playing the game?

Single Player - No Server

### What happened?

the `Blue Standing Brazier` is not being affected by the mod.
Didn't try the standard `Standing Brazier`

### Screenshots

![image](https://github.com/Digitalroot-Valheim/Digitalroot.Valheim.EternalFire/assets/6009914/e839b54a-721d-4449-9eca-6488d79b6009)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Digitalroot** [comment]
IronFirePit is missing too

**Comment by Digitalroot** [comment]
Fixed in v1.0.8
